// Menu Reducer types
export const LOADING_MENU_FAILURE = 'LOADING_MENU_FAILURE';
export const LOADING_MENU_REQUEST = 'LOADING_MENU_REQUEST';
export const LOADING_MENU_SUCCESS = 'LOADING_MENU_SUCCESS';
export const SET_MENU = 'SET_MENU';
export const SET_MENU_ITEM = 'SET_MENU_ITEM';

// Order reducer types
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SET_CART_PAYMENT_INFORMATION = 'SET_CART_PAYMENT_INFORMATION';
export const SET_ORDER = 'SET_ORDER';

// UI reducer types
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const LOADING_UI_SUCCESS = 'LOADING_UI_SUCCESS';
export const SET_ERRORS = 'SET_ERRORS';

// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_ANONYMOUS = 'SET_ANONYMOUS';
